baseURL = "https://nemiron.me/"
title = "Nemiron blog"
enableRobotsTXT = true
copyright = "© {year} Pavel Aleksandrov"
# disqusShortname = "Nemiron"
googleAnalytics = "UA-173573553-1" 

# Theme settings
theme = "hugo-theme-codex"
# enableEmoji = true
# showMenuLanguageChooser = true

# # Languages
# defaultContentLanguage = "ru"           # Default language to use
# [languages]
# [languages.en]
#   title = "Blog nemiron.me"
#   weight = 1
#   LanguageName = "English"
# [languages.ru]
#   title = "Блог nemiron.me"
#   weight = 2
#   LanguageName = "По-русски"

languageCode = "ru"



# Optional params
[params]
  dateFormat = "Jan 2 2006"

  # Social networks
  # Currently, these icons are supported: 
  # "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube", "Telegram"
  github = "https://github.com/Nemironium"
  email = "mailto:nemiron@outlook.com"
  linkedin = "https://linkedin.com/in/pavelaleksandrov"
  telegram = "https://t.me/nemiron"
  instagram = "https://www.instagram.com/nemironium/"
  iconTitles = ["GitHub", "Email", "LinkedIn", "Telegram", "Instagram"]


# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "cv"
  name = "CV"
  title = "CV"
  url = "/cv"
