---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: slug
  label: slug
  description: The post filename
- type: text
  name: description
  label: description
  description: Post description used for SEO
- type: list
  name: keywords
  label: keywords
  description: Post keywords used for SEO
- type: list
  name: tags
  label: tags
- type: boolean
  name: math
  label: math
- type: boolean
  name: toc
  label: toc
  description: Includes a table of contents on screens &gt;1024px
